### ISSUE TITLE
`brew install oxigraph` terminates with the following message:

### ISSUE THREAD

**Issue by mpagni12** [oxigraph/homebrew-oxigraph#4]
==> cargo install --root /opt/homebrew/Cellar/oxigraph/0.4.0-alpha.6 --path server
Last 15 lines from /Users/mpagni/Library/Logs/Homebrew/oxigraph/01.cargo:

cargo
install
--locked
--root
/opt/homebrew/Cellar/oxigraph/0.4.0-alpha.6
--path
server

error: current package believes it's in a workspace when it's not:
current:   /private/tmp/oxigraph-20240504-13757-go5e50/server/Cargo.toml
workspace: /private/tmp/oxigraph-20240504-13757-go5e50/Cargo.toml

this may be fixable by adding `server` to the `workspace.members` array of the manifest located at: /private/tmp/oxigraph-20240504-13757-go5e50/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/oxigraph/homebrew-oxigraph/issues

**Comment by Tpt** [comment]
Thank you so much for this bug report and sorry for that. I thaught the script that pushes new releases to this repo would skip alpha versions but it seems it does not. I have renamed the `server` directory to `cli` in the 4.0 version. #5 should fix the issue

**Comment by mpagni12** [comment]
Now it works ;-))  Thanks a lot. 

Reporting an error here with a single cut and paste was really very very convenient
